M04Ref2S.title   マスタ参照２検索
M04Ref2S.h2      マスタ参照２検索
M04Ref2S.legend  マスタ参照２検索
M04Ref2.add      マスタ参照２追加
M04Ref2.title    マスタ参照２
M04Ref2.h2       マスタ参照２
M04Ref2.legend   マスタ参照２
M04Ref2.h3       マスタ参照２一覧

M04Ref2.ref2Id 参照２ID
M04Ref2.ref2Mei 参照２名
M04Ref2.deleteF 削除フラグ
M04Ref2.tekiyoBi 適用日
M04Ref2.haishiBi 廃止日
M04Ref2.insertTs 作成タイムスタンプ
M04Ref2.insertUserId 作成者
M04Ref2.updateTs 更新タイムスタンプ
M04Ref2.updateUserId 更新者

M04Ref2Grid.ref2Id 参照２ID
M04Ref2Grid.ref2Mei 参照２名
M04Ref2Grid.deleteF 削除フラグ
M04Ref2Grid.tekiyoBi 適用日
M04Ref2Grid.haishiBi 廃止日
M04Ref2Grid.insertTs 作成タイムスタンプ
M04Ref2Grid.insertUserId 作成者
M04Ref2Grid.updateTs 更新タイムスタンプ
M04Ref2Grid.updateUserId 更新者
