M04Ref3S.title   マスタ参照３検索
M04Ref3S.h2      マスタ参照３検索
M04Ref3S.legend  マスタ参照３検索
M04Ref3.add      マスタ参照３追加
M04Ref3.title    マスタ参照３
M04Ref3.h2       マスタ参照３
M04Ref3.legend   マスタ参照３
M04Ref3.h3       マスタ参照３一覧

M04Ref3.ref3Id 参照３ID
M04Ref3.ref3Mei 参照３名
M04Ref3.deleteF 削除フラグ
M04Ref3.tekiyoBi 適用日
M04Ref3.haishiBi 廃止日
M04Ref3.insertTs 作成タイムスタンプ
M04Ref3.insertUserId 作成者
M04Ref3.updateTs 更新タイムスタンプ
M04Ref3.updateUserId 更新者

M04Ref3Grid.ref3Id 参照３ID
M04Ref3Grid.ref3Mei 参照３名
M04Ref3Grid.deleteF 削除フラグ
M04Ref3Grid.tekiyoBi 適用日
M04Ref3Grid.haishiBi 廃止日
M04Ref3Grid.insertTs 作成タイムスタンプ
M04Ref3Grid.insertUserId 作成者
M04Ref3Grid.updateTs 更新タイムスタンプ
M04Ref3Grid.updateUserId 更新者
