M05CdS.title   CDマスタ検索
M05CdS.h2      CDマスタ検索
M05CdS.legend  CDマスタ検索
M05Cd.add      CDマスタ追加
M05Cd.title    CDマスタ
M05Cd.h2       CDマスタ
M05Cd.legend   CDマスタ
M05Cd.h3       CDマスタ一覧

M05Cd.cdrefCd 参照CD
M05Cd.cdrefMei CD参照名
M05Cd.insertTs 作成タイムスタンプ
M05Cd.insertUserId 作成者
M05Cd.updateTs 更新タイムスタンプ
M05Cd.updateUserId 更新者

M05CdGrid.cdrefCd 参照CD
M05CdGrid.cdrefMei CD参照名
M05CdGrid.insertTs 作成タイムスタンプ
M05CdGrid.insertUserId 作成者
M05CdGrid.updateTs 更新タイムスタンプ
M05CdGrid.updateUserId 更新者
