M05IdS.title   IDマスタ検索
M05IdS.h2      IDマスタ検索
M05IdS.legend  IDマスタ検索
M05Id.add      IDマスタ追加
M05Id.title    IDマスタ
M05Id.h2       IDマスタ
M05Id.legend   IDマスタ
M05Id.h3       IDマスタ一覧

M05Id.idrefId 参照ID
M05Id.idrefMei ID参照名
M05Id.insertTs 作成タイムスタンプ
M05Id.insertUserId 作成者
M05Id.updateTs 更新タイムスタンプ
M05Id.updateUserId 更新者

M05IdGrid.idrefId 参照ID
M05IdGrid.idrefMei ID参照名
M05IdGrid.insertTs 作成タイムスタンプ
M05IdGrid.insertUserId 作成者
M05IdGrid.updateTs 更新タイムスタンプ
M05IdGrid.updateUserId 更新者

M05Idbn.h3  ID連番マスタ一覧
M05Idbn.add ID連番マスタ追加
M05IdbnGrid.idrefId 参照ID
M05IdbnGrid.idbnBn 参照連番
M05IdbnGrid.idbnNo ID連番NO
M05IdbnGrid.insertTs 作成タイムスタンプ
M05IdbnGrid.insertUserId 作成者
M05IdbnGrid.updateTs 更新タイムスタンプ
M05IdbnGrid.updateUserId 更新者
