M05NoS.title   NOマスタ検索
M05NoS.h2      NOマスタ検索
M05NoS.legend  NOマスタ検索
M05No.add      NOマスタ追加
M05No.title    NOマスタ
M05No.h2       NOマスタ
M05No.legend   NOマスタ
M05No.h3       NOマスタ一覧

M05No.norefNo 参照NO
M05No.norefMei NO参照名
M05No.insertTs 作成タイムスタンプ
M05No.insertUserId 作成者
M05No.updateTs 更新タイムスタンプ
M05No.updateUserId 更新者

M05NoGrid.norefNo 参照NO
M05NoGrid.norefMei NO参照名
M05NoGrid.insertTs 作成タイムスタンプ
M05NoGrid.insertUserId 作成者
M05NoGrid.updateTs 更新タイムスタンプ
M05NoGrid.updateUserId 更新者
