M05SaikiS.title   再帰検索
M05SaikiS.h2      再帰検索
M05SaikiS.legend  再帰検索
M05Saiki.add      再帰追加
M05Saiki.title    再帰
M05Saiki.h2       再帰
M05Saiki.legend   再帰
M05Saiki.h3       再帰一覧

M05Saiki.saikiId 再帰ID
M05Saiki.saikiMei 再帰名
M05Saiki.idrefId 参照ID
M05Saiki.cdrefCd 参照CD
M05Saiki.norefNo 参照NO
M05Saiki.exIdrefId ID連番ID
M05Saiki.exIdbnBn ID連番
M05Saiki.oyaSaikiId 親再帰ID
M05Saiki.insertTs 作成タイムスタンプ
M05Saiki.insertUserId 作成者
M05Saiki.updateTs 更新タイムスタンプ
M05Saiki.updateUserId 更新者

M05SaikiGrid.saikiId 再帰ID
M05SaikiGrid.saikiMei 再帰名
M05SaikiGrid.idrefId 参照ID
M05SaikiGrid.cdrefCd 参照CD
M05SaikiGrid.norefNo 参照NO
M05SaikiGrid.exIdrefId ID連番ID
M05SaikiGrid.exIdbnBn ID連番
M05SaikiGrid.oyaSaikiId 親再帰ID
M05SaikiGrid.insertTs 作成タイムスタンプ
M05SaikiGrid.insertUserId 作成者
M05SaikiGrid.updateTs 更新タイムスタンプ
M05SaikiGrid.updateUserId 更新者
