T00JissekiS.title   実績検索
T00JissekiS.h2      実績検索
T00JissekiS.legend  実績検索
T00Jisseki.add      実績追加
T00Jisseki.title    実績
T00Jisseki.h2       実績
T00Jisseki.legend   実績
T00Jisseki.h3       実績一覧

T00Jisseki.kouteiId 工程ID
T00Jisseki.jissekiBn 実績連番
T00Jisseki.jisshiBi 実施日
T00Jisseki.kanryoBi 完了日
T00Jisseki.insertTs 作成タイムスタンプ
T00Jisseki.insertUserId 作成者
T00Jisseki.updateTs 更新タイムスタンプ
T00Jisseki.updateUserId 更新者

T00JissekiGrid.kouteiId 工程ID
T00JissekiGrid.jissekiBn 実績連番
T00JissekiGrid.jisshiBi 実施日
T00JissekiGrid.kanryoBi 完了日
T00JissekiGrid.insertTs 作成タイムスタンプ
T00JissekiGrid.insertUserId 作成者
T00JissekiGrid.updateTs 更新タイムスタンプ
T00JissekiGrid.updateUserId 更新者
