T00KouteiS.title   工程検索
T00KouteiS.h2      工程検索
T00KouteiS.legend  工程検索
T00Koutei.add      工程追加
T00Koutei.title    工程
T00Koutei.h2       工程
T00Koutei.legend   工程
T00Koutei.h3       工程一覧

T00Koutei.kouteiId 工程ID
T00Koutei.kouteiMei 工程名
T00Koutei.kaishiBi 開始日
T00Koutei.shuryoBi 終了日
T00Koutei.oyaKouteiId 親工程ID
T00Koutei.insertTs 作成タイムスタンプ
T00Koutei.insertUserId 作成者
T00Koutei.updateTs 更新タイムスタンプ
T00Koutei.updateUserId 更新者

T00KouteiGrid.kouteiId 工程ID
T00KouteiGrid.kouteiMei 工程名
T00KouteiGrid.kaishiBi 開始日
T00KouteiGrid.shuryoBi 終了日
T00KouteiGrid.oyaKouteiId 親工程ID
T00KouteiGrid.insertTs 作成タイムスタンプ
T00KouteiGrid.insertUserId 作成者
T00KouteiGrid.updateTs 更新タイムスタンプ
T00KouteiGrid.updateUserId 更新者
