T00StatusKbS.title   決裁フロー検索
T00StatusKbS.h2      決裁フロー検索
T00StatusKbS.legend  決裁フロー検索
T00StatusKb.add      決裁フロー追加
T00StatusKb.title    決裁フロー
T00StatusKb.h2       決裁フロー
T00StatusKb.legend   決裁フロー
T00StatusKb.h3       決裁フロー一覧

T00StatusKb.flowId フローID
T00StatusKb.tableNm テーブル名称
T00StatusKb.primaryKeys 主キー
T00StatusKb.statusKb ステータス区分
T00StatusKb.kessaiTs 決裁タイムスタンプ
T00StatusKb.kessaiId 決裁者ID
T00StatusKb.riyuTx 決裁コメント
T00StatusKb.insertTs 作成タイムスタンプ
T00StatusKb.insertUserId 作成者
T00StatusKb.updateTs 更新タイムスタンプ
T00StatusKb.updateUserId 更新者

T00StatusKbGrid.flowId フローID
T00StatusKbGrid.tableNm テーブル名称
T00StatusKbGrid.primaryKeys 主キー
T00StatusKbGrid.statusKb ステータス区分
T00StatusKbGrid.kessaiTs 決裁タイムスタンプ
T00StatusKbGrid.kessaiId 決裁者ID
T00StatusKbGrid.riyuTx 決裁コメント
T00StatusKbGrid.insertTs 作成タイムスタンプ
T00StatusKbGrid.insertUserId 作成者
T00StatusKbGrid.updateTs 更新タイムスタンプ
T00StatusKbGrid.updateUserId 更新者
