T00UniqueS.title   ユニークキー検索
T00UniqueS.h2      ユニークキー検索
T00UniqueS.legend  ユニークキー検索
T00Unique.add      ユニークキー追加
T00Unique.title    ユニークキー
T00Unique.h2       ユニークキー
T00Unique.legend   ユニークキー
T00Unique.h3       ユニークキー一覧

T00Unique.aMei 列Ａ
T00Unique.bMei 列Ｂ
T00Unique.cMei 列Ｃ
T00Unique.dMei 列Ｄ
T00Unique.eMei 列Ｅ
T00Unique.insertTs 作成タイムスタンプ
T00Unique.insertUserId 作成者
T00Unique.updateTs 更新タイムスタンプ
T00Unique.updateUserId 更新者

T00UniqueGrid.aMei 列Ａ
T00UniqueGrid.bMei 列Ｂ
T00UniqueGrid.cMei 列Ｃ
T00UniqueGrid.dMei 列Ｄ
T00UniqueGrid.eMei 列Ｅ
T00UniqueGrid.insertTs 作成タイムスタンプ
T00UniqueGrid.insertUserId 作成者
T00UniqueGrid.updateTs 更新タイムスタンプ
T00UniqueGrid.updateUserId 更新者
