T01EldestS.title   長兄検索
T01EldestS.h2      長兄検索
T01EldestS.legend  長兄検索
T01Eldest.add      長兄追加
T01Eldest.title    長兄
T01Eldest.h2       長兄
T01Eldest.legend   長兄
T01Eldest.h3       長兄一覧

T01Eldest.broId 兄弟ID
T01Eldest.eldestInfo 長兄情報
T01Eldest.insertTs 作成タイムスタンプ
T01Eldest.insertUserId 作成者
T01Eldest.updateTs 更新タイムスタンプ
T01Eldest.updateUserId 更新者

T01EldestGrid.broId 兄弟ID
T01EldestGrid.eldestInfo 長兄情報
T01EldestGrid.insertTs 作成タイムスタンプ
T01EldestGrid.insertUserId 作成者
T01EldestGrid.updateTs 更新タイムスタンプ
T01EldestGrid.updateUserId 更新者
T01EldestGrid.youngerInfo 弟情報
T01EldestGrid.youngestInfo 末弟情報

T01Younger.legend   弟
T01Younger.broId 兄弟ID
T01Younger.youngerInfo 弟情報
T01Younger.insertTs 作成タイムスタンプ
T01Younger.insertUserId 作成者
T01Younger.updateTs 更新タイムスタンプ
T01Younger.updateUserId 更新者

T01Youngest.legend   末弟
T01Youngest.broId 兄弟ID
T01Youngest.youngestInfo 末弟情報
T01Youngest.insertTs 作成タイムスタンプ
T01Youngest.insertUserId 作成者
T01Youngest.updateTs 更新タイムスタンプ
T01Youngest.updateUserId 更新者
