T01YoungerS.title   弟検索
T01YoungerS.h2      弟検索
T01YoungerS.legend  弟検索
T01Younger.add      弟追加
T01Younger.title    弟
T01Younger.h2       弟
T01Younger.legend   弟
T01Younger.h3       弟一覧

T01Younger.broId 兄弟ID
T01Younger.youngerInfo 弟情報
T01Younger.insertTs 作成タイムスタンプ
T01Younger.insertUserId 作成者
T01Younger.updateTs 更新タイムスタンプ
T01Younger.updateUserId 更新者

T01YoungerGrid.broId 兄弟ID
T01YoungerGrid.youngerInfo 弟情報
T01YoungerGrid.insertTs 作成タイムスタンプ
T01YoungerGrid.insertUserId 作成者
T01YoungerGrid.updateTs 更新タイムスタンプ
T01YoungerGrid.updateUserId 更新者
T01YoungerGrid.youngestInfo 末弟情報

T01Youngest.legend   末弟
T01Youngest.broId 兄弟ID
T01Youngest.youngestInfo 末弟情報
T01Youngest.insertTs 作成タイムスタンプ
T01Youngest.insertUserId 作成者
T01Youngest.updateTs 更新タイムスタンプ
T01Youngest.updateUserId 更新者
