T02MagoS.title   孫検索
T02MagoS.h2      孫検索
T02MagoS.legend  孫検索
T02Mago.add      孫追加
T02Mago.title    孫
T02Mago.h2       孫
T02Mago.legend   孫
T02Mago.h3       孫一覧

T02Mago.oyaId 親ID
T02Mago.koBn 子枝番
T02Mago.magoBn 孫枝番
T02Mago.magoInfo 孫情報
T02Mago.insertTs 作成タイムスタンプ
T02Mago.insertUserId 作成者
T02Mago.updateTs 更新タイムスタンプ
T02Mago.updateUserId 更新者

T02MagoGrid.oyaId 親ID
T02MagoGrid.koBn 子枝番
T02MagoGrid.magoBn 孫枝番
T02MagoGrid.magoInfo 孫情報
T02MagoGrid.insertTs 作成タイムスタンプ
T02MagoGrid.insertUserId 作成者
T02MagoGrid.updateTs 更新タイムスタンプ
T02MagoGrid.updateUserId 更新者

T02Dinks.legend   子なし
T02Dinks.oyaId 親ID
T02Dinks.koBn 子枝番
T02Dinks.dinksInfo 子なし情報
T02Dinks.insertTs 作成タイムスタンプ
T02Dinks.insertUserId 作成者
T02Dinks.updateTs 更新タイムスタンプ
T02Dinks.updateUserId 更新者

T02Ko.legend   子
T02Ko.oyaId 親ID
T02Ko.koBn 子枝番
T02Ko.koInfo 子情報
T02Ko.insertTs 作成タイムスタンプ
T02Ko.insertUserId 作成者
T02Ko.updateTs 更新タイムスタンプ
T02Ko.updateUserId 更新者

T02Orphan.legend   孤児
T02Orphan.oyaId 親ID
T02Orphan.koBn 子枝番
T02Orphan.orphanInfo 孤児情報
T02Orphan.insertTs 作成タイムスタンプ
T02Orphan.insertUserId 作成者
T02Orphan.updateTs 更新タイムスタンプ
T02Orphan.updateUserId 更新者
