T02OyaS.title   親検索
T02OyaS.h2      親検索
T02OyaS.legend  親検索
T02Oya.add      親追加
T02Oya.title    親
T02Oya.h2       親
T02Oya.legend   親
T02Oya.h3       親一覧

T02Oya.oyaId 親ID
T02Oya.oyaInfo 親情報
T02Oya.insertTs 作成タイムスタンプ
T02Oya.insertUserId 作成者
T02Oya.updateTs 更新タイムスタンプ
T02Oya.updateUserId 更新者

T02OyaGrid.oyaId 親ID
T02OyaGrid.oyaInfo 親情報
T02OyaGrid.insertTs 作成タイムスタンプ
T02OyaGrid.insertUserId 作成者
T02OyaGrid.updateTs 更新タイムスタンプ
T02OyaGrid.updateUserId 更新者

T02Dinks.h3  子なし一覧
T02Dinks.add 子なし追加
T02DinksGrid.oyaId 親ID
T02DinksGrid.koBn 子枝番
T02DinksGrid.dinksInfo 子なし情報
T02DinksGrid.insertTs 作成タイムスタンプ
T02DinksGrid.insertUserId 作成者
T02DinksGrid.updateTs 更新タイムスタンプ
T02DinksGrid.updateUserId 更新者

T02Ko.h3  子一覧
T02Ko.add 子追加
T02KoGrid.oyaId 親ID
T02KoGrid.koBn 子枝番
T02KoGrid.koInfo 子情報
T02KoGrid.insertTs 作成タイムスタンプ
T02KoGrid.insertUserId 作成者
T02KoGrid.updateTs 更新タイムスタンプ
T02KoGrid.updateUserId 更新者
