T03StatusKbS.title   決裁フロー検索
T03StatusKbS.h2      決裁フロー検索
T03StatusKbS.legend  決裁フロー検索
T03StatusKb.add      決裁フロー追加
T03StatusKb.title    決裁フロー
T03StatusKb.h2       決裁フロー
T03StatusKb.legend   決裁フロー
T03StatusKb.h3       決裁フロー一覧

T03StatusKb.flowId フローID
T03StatusKb.tableNm テーブル名称
T03StatusKb.primaryKeys 主キー
T03StatusKb.statusKb ステータス区分
T03StatusKb.kessaiTs 決裁タイムスタンプ
T03StatusKb.kessaiId 決裁者ID
T03StatusKb.kessaiTx 決裁理由
T03StatusKb.insertTs 作成タイムスタンプ
T03StatusKb.insertUserId 作成者
T03StatusKb.updateTs 更新タイムスタンプ
T03StatusKb.updateUserId 更新者

T03StatusKbGrid.flowId フローID
T03StatusKbGrid.tableNm テーブル名称
T03StatusKbGrid.primaryKeys 主キー
T03StatusKbGrid.statusKb ステータス区分
T03StatusKbGrid.kessaiTs 決裁タイムスタンプ
T03StatusKbGrid.kessaiId 決裁者ID
T03StatusKbGrid.kessaiTx 決裁理由
T03StatusKbGrid.insertTs 作成タイムスタンプ
T03StatusKbGrid.insertUserId 作成者
T03StatusKbGrid.updateTs 更新タイムスタンプ
T03StatusKbGrid.updateUserId 更新者
