T04Comp2S.title   複合２検索
T04Comp2S.h2      複合２検索
T04Comp2S.legend  複合２検索
T04Comp2.add      複合２追加
T04Comp2.title    複合２
T04Comp2.h2       複合２
T04Comp2.legend   複合２
T04Comp2.h3       複合２一覧

T04Comp2.ref1Id 参照１ID
T04Comp2.ref2Id 参照２ID
T04Comp2.ref3Id 参照３ID
T04Comp2.tekiyoBi 適用日
T04Comp2.comp2Info 複合２情報
T04Comp2.insertTs 作成タイムスタンプ
T04Comp2.insertUserId 作成者
T04Comp2.updateTs 更新タイムスタンプ
T04Comp2.updateUserId 更新者

T04Comp2Grid.ref1Id 参照１ID
T04Comp2Grid.ref2Id 参照２ID
T04Comp2Grid.ref3Id 参照３ID
T04Comp2Grid.tekiyoBi 適用日
T04Comp2Grid.comp2Info 複合２情報
T04Comp2Grid.insertTs 作成タイムスタンプ
T04Comp2Grid.insertUserId 作成者
T04Comp2Grid.updateTs 更新タイムスタンプ
T04Comp2Grid.updateUserId 更新者

T04Comp1.legend   複合１
T04Comp1.ref1Id 参照１ID
T04Comp1.ref2Id 参照２ID
T04Comp1.comp1Mei 複合１名
T04Comp1.insertTs 作成タイムスタンプ
T04Comp1.insertUserId 作成者
T04Comp1.updateTs 更新タイムスタンプ
T04Comp1.updateUserId 更新者
