T06PrevS.title   前世検索
T06PrevS.h2      前世検索
T06PrevS.legend  前世検索
T06Prev.add      前世追加
T06Prev.title    前世
T06Prev.h2       前世
T06Prev.legend   前世
T06Prev.h3       前世一覧

T06Prev.prevId 前世ID
T06Prev.prevInfo 前世情報
T06Prev.insertTs 作成タイムスタンプ
T06Prev.insertUserId 作成者
T06Prev.updateTs 更新タイムスタンプ
T06Prev.updateUserId 更新者

T06PrevGrid.prevId 前世ID
T06PrevGrid.prevInfo 前世情報
T06PrevGrid.insertTs 作成タイムスタンプ
T06PrevGrid.insertUserId 作成者
T06PrevGrid.updateTs 更新タイムスタンプ
T06PrevGrid.updateUserId 更新者

T06PrevDet.h3  前世明細一覧
T06PrevDet.add 前世明細追加
T06PrevDetGrid.prevId 前世ID
T06PrevDetGrid.prevBn 前世枝番
T06PrevDetGrid.detInfo 明細情報
T06PrevDetGrid.insertTs 作成タイムスタンプ
T06PrevDetGrid.insertUserId 作成者
T06PrevDetGrid.updateTs 更新タイムスタンプ
T06PrevDetGrid.updateUserId 更新者

T06Reborn.h3  転生一覧
T06Reborn.add 転生追加
T06RebornGrid.rebornId 転生ID
T06RebornGrid.prevInfo 前世情報
T06RebornGrid.prevId 前世ID
T06RebornGrid.insertTs 作成タイムスタンプ
T06RebornGrid.insertUserId 作成者
T06RebornGrid.updateTs 更新タイムスタンプ
T06RebornGrid.updateUserId 更新者
