T06RebornS.title   転生検索
T06RebornS.h2      転生検索
T06RebornS.legend  転生検索
T06Reborn.add      転生追加
T06Reborn.title    転生
T06Reborn.h2       転生
T06Reborn.legend   転生
T06Reborn.h3       転生一覧

T06Reborn.rebornId 転生ID
T06Reborn.prevInfo 前世情報
T06Reborn.prevId 前世ID
T06Reborn.insertTs 作成タイムスタンプ
T06Reborn.insertUserId 作成者
T06Reborn.updateTs 更新タイムスタンプ
T06Reborn.updateUserId 更新者

T06RebornGrid.rebornId 転生ID
T06RebornGrid.prevInfo 前世情報
T06RebornGrid.prevId 前世ID
T06RebornGrid.insertTs 作成タイムスタンプ
T06RebornGrid.insertUserId 作成者
T06RebornGrid.updateTs 更新タイムスタンプ
T06RebornGrid.updateUserId 更新者

T06RebornDet.h3  転生明細一覧
T06RebornDet.add 転生明細追加
T06RebornDetGrid.rebornId 転生ID
T06RebornDetGrid.rebornBn 転生枝番
T06RebornDetGrid.detInfo 明細情報
T06RebornDetGrid.insertTs 作成タイムスタンプ
T06RebornDetGrid.insertUserId 作成者
T06RebornDetGrid.updateTs 更新タイムスタンプ
T06RebornDetGrid.updateUserId 更新者
