T07Derive1DetS.title   派生１明細検索
T07Derive1DetS.h2      派生１明細検索
T07Derive1DetS.legend  派生１明細検索
T07Derive1Det.add      派生１明細追加
T07Derive1Det.title    派生１明細
T07Derive1Det.h2       派生１明細
T07Derive1Det.legend   派生１明細
T07Derive1Det.h3       派生１明細一覧

T07Derive1Det.derive1Id 派生１ID
T07Derive1Det.derive1Bn 派生１枝番
T07Derive1Det.detInfo 明細情報
T07Derive1Det.insertTs 作成タイムスタンプ
T07Derive1Det.insertUserId 作成者
T07Derive1Det.updateTs 更新タイムスタンプ
T07Derive1Det.updateUserId 更新者

T07Derive1DetGrid.derive1Id 派生１ID
T07Derive1DetGrid.derive1Bn 派生１枝番
T07Derive1DetGrid.detInfo 明細情報
T07Derive1DetGrid.insertTs 作成タイムスタンプ
T07Derive1DetGrid.insertUserId 作成者
T07Derive1DetGrid.updateTs 更新タイムスタンプ
T07Derive1DetGrid.updateUserId 更新者

T07Derive1.legend   派生１
T07Derive1.derive1Id 派生１ID
T07Derive1.orgInfo 起源情報
T07Derive1.orgId 起源ID
T07Derive1.insertTs 作成タイムスタンプ
T07Derive1.insertUserId 作成者
T07Derive1.updateTs 更新タイムスタンプ
T07Derive1.updateUserId 更新者
