T07OrgDetS.title   起源明細検索
T07OrgDetS.h2      起源明細検索
T07OrgDetS.legend  起源明細検索
T07OrgDet.add      起源明細追加
T07OrgDet.title    起源明細
T07OrgDet.h2       起源明細
T07OrgDet.legend   起源明細
T07OrgDet.h3       起源明細一覧

T07OrgDet.orgId 起源ID
T07OrgDet.orgBn 起源枝番
T07OrgDet.detInfo 明細情報
T07OrgDet.insertTs 作成タイムスタンプ
T07OrgDet.insertUserId 作成者
T07OrgDet.updateTs 更新タイムスタンプ
T07OrgDet.updateUserId 更新者

T07OrgDetGrid.orgId 起源ID
T07OrgDetGrid.orgBn 起源枝番
T07OrgDetGrid.detInfo 明細情報
T07OrgDetGrid.insertTs 作成タイムスタンプ
T07OrgDetGrid.insertUserId 作成者
T07OrgDetGrid.updateTs 更新タイムスタンプ
T07OrgDetGrid.updateUserId 更新者

T07Org.legend   起源
T07Org.orgId 起源ID
T07Org.orgInfo 起源情報
T07Org.insertTs 作成タイムスタンプ
T07Org.insertUserId 作成者
T07Org.updateTs 更新タイムスタンプ
T07Org.updateUserId 更新者
