T07OrgS.title   起源検索
T07OrgS.h2      起源検索
T07OrgS.legend  起源検索
T07Org.add      起源追加
T07Org.title    起源
T07Org.h2       起源
T07Org.legend   起源
T07Org.h3       起源一覧

T07Org.orgId 起源ID
T07Org.orgInfo 起源情報
T07Org.insertTs 作成タイムスタンプ
T07Org.insertUserId 作成者
T07Org.updateTs 更新タイムスタンプ
T07Org.updateUserId 更新者

T07OrgGrid.orgId 起源ID
T07OrgGrid.orgInfo 起源情報
T07OrgGrid.insertTs 作成タイムスタンプ
T07OrgGrid.insertUserId 作成者
T07OrgGrid.updateTs 更新タイムスタンプ
T07OrgGrid.updateUserId 更新者

T07OrgDet.h3  起源明細一覧
T07OrgDet.add 起源明細追加
T07OrgDetGrid.orgId 起源ID
T07OrgDetGrid.orgBn 起源枝番
T07OrgDetGrid.detInfo 明細情報
T07OrgDetGrid.insertTs 作成タイムスタンプ
T07OrgDetGrid.insertUserId 作成者
T07OrgDetGrid.updateTs 更新タイムスタンプ
T07OrgDetGrid.updateUserId 更新者

T07Derive1.add 派生１追加

T07Derive2.add 派生２追加
