T09ChoiceS.title   選択検索
T09ChoiceS.h2      選択検索
T09ChoiceS.legend  選択検索
T09Choice.add      選択追加
T09Choice.title    選択
T09Choice.h2       選択
T09Choice.legend   選択
T09Choice.h3       選択一覧

T09Choice.choiceId 選択ID
T09Choice.koho1Id 候補１ID
T09Choice.koho1Info 候補１情報
T09Choice.koho2Id 候補２ID
T09Choice.koho2Info 候補２情報
T09Choice.insertTs 作成タイムスタンプ
T09Choice.insertUserId 作成者
T09Choice.updateTs 更新タイムスタンプ
T09Choice.updateUserId 更新者

T09ChoiceGrid.choiceId 選択ID
T09ChoiceGrid.koho1Id 候補１ID
T09ChoiceGrid.koho1Info 候補１情報
T09ChoiceGrid.koho2Id 候補２ID
T09ChoiceGrid.koho2Info 候補２情報
T09ChoiceGrid.insertTs 作成タイムスタンプ
T09ChoiceGrid.insertUserId 作成者
T09ChoiceGrid.updateTs 更新タイムスタンプ
T09ChoiceGrid.updateUserId 更新者
