T09Koho2S.title   候補２検索
T09Koho2S.h2      候補２検索
T09Koho2S.legend  候補２検索
T09Koho2.add      候補２追加
T09Koho2.title    候補２
T09Koho2.h2       候補２
T09Koho2.legend   候補２
T09Koho2.h3       候補２一覧

T09Koho2.koho2Id 候補２ID
T09Koho2.koho2Info 候補２情報
T09Koho2.insertTs 作成タイムスタンプ
T09Koho2.insertUserId 作成者
T09Koho2.updateTs 更新タイムスタンプ
T09Koho2.updateUserId 更新者

T09Koho2Grid.koho2Id 候補２ID
T09Koho2Grid.koho2Info 候補２情報
T09Koho2Grid.insertTs 作成タイムスタンプ
T09Koho2Grid.insertUserId 作成者
T09Koho2Grid.updateTs 更新タイムスタンプ
T09Koho2Grid.updateUserId 更新者

T09Choice.add 選抜追加
