T10Grp2S.title   集団２検索
T10Grp2S.h2      集団２検索
T10Grp2S.legend  集団２検索
T10Grp2.add      集団２追加
T10Grp2.title    集団２
T10Grp2.h2       集団２
T10Grp2.legend   集団２
T10Grp2.h3       集団２一覧

T10Grp2.grp2Id 集団２ID
T10Grp2.sumId 集約ID
T10Grp2.insertTs 作成タイムスタンプ
T10Grp2.insertUserId 作成者
T10Grp2.updateTs 更新タイムスタンプ
T10Grp2.updateUserId 更新者

T10Grp2Grid.grp2Id 集団２ID
T10Grp2Grid.sumId 集約ID
T10Grp2Grid.insertTs 作成タイムスタンプ
T10Grp2Grid.insertUserId 作成者
T10Grp2Grid.updateTs 更新タイムスタンプ
T10Grp2Grid.updateUserId 更新者

T10Sum.sum 集約集約
