T10Grp1S.title   集団１検索
T10Grp1S.h2      集団１検索
T10Grp1S.legend  集団１検索
T10Grp1.add      集団１追加
T10Grp1.title    集団１
T10Grp1.h2       集団１
T10Grp1.legend   集団１
T10Grp1.h3       集団１一覧

T10Grp1.grp1Id 集団１ID
T10Grp1.sumId 集約ID
T10Grp1.insertTs 作成タイムスタンプ
T10Grp1.insertUserId 作成者
T10Grp1.updateTs 更新タイムスタンプ
T10Grp1.updateUserId 更新者

T10Grp1Grid.grp1Id 集団１ID
T10Grp1Grid.sumId 集約ID
T10Grp1Grid.insertTs 作成タイムスタンプ
T10Grp1Grid.insertUserId 作成者
T10Grp1Grid.updateTs 更新タイムスタンプ
T10Grp1Grid.updateUserId 更新者

T10Sum.sum 集約集約
