T10SumS.title   集約検索
T10SumS.h2      集約検索
T10SumS.legend  集約検索
T10Sum.add      集約追加
T10Sum.title    集約
T10Sum.h2       集約
T10Sum.legend   集約
T10Sum.h3       集約一覧

T10Sum.sumId 集約ID
T10Sum.sumInfo 集約情報
T10Sum.insertTs 作成タイムスタンプ
T10Sum.insertUserId 作成者
T10Sum.updateTs 更新タイムスタンプ
T10Sum.updateUserId 更新者

T10SumGrid.sumId 集約ID
T10SumGrid.sumInfo 集約情報
T10SumGrid.insertTs 作成タイムスタンプ
T10SumGrid.insertUserId 作成者
T10SumGrid.updateTs 更新タイムスタンプ
T10SumGrid.updateUserId 更新者

T10Grp1.add 集団１追加

T10Grp2.add 集団２追加
