T14JissekiS.title   実績検索
T14JissekiS.h2      実績検索
T14JissekiS.legend  実績検索
T14Jisseki.add      実績追加
T14Jisseki.title    実績
T14Jisseki.h2       実績
T14Jisseki.legend   実績
T14Jisseki.h3       実績一覧

T14Jisseki.kouteiId 工程ID
T14Jisseki.jissekiBn 実績連番
T14Jisseki.jisshiBi 実施日
T14Jisseki.kanryoBi 完了日
T14Jisseki.insertTs 作成タイムスタンプ
T14Jisseki.insertUserId 作成者
T14Jisseki.updateTs 更新タイムスタンプ
T14Jisseki.updateUserId 更新者

T14JissekiGrid.kouteiId 工程ID
T14JissekiGrid.jissekiBn 実績連番
T14JissekiGrid.jisshiBi 実施日
T14JissekiGrid.kanryoBi 完了日
T14JissekiGrid.insertTs 作成タイムスタンプ
T14JissekiGrid.insertUserId 作成者
T14JissekiGrid.updateTs 更新タイムスタンプ
T14JissekiGrid.updateUserId 更新者
