T14KouteiS.title   工程検索
T14KouteiS.h2      工程検索
T14KouteiS.legend  工程検索
T14Koutei.add      工程追加
T14Koutei.title    工程
T14Koutei.h2       工程
T14Koutei.legend   工程
T14Koutei.h3       工程一覧

T14Koutei.kouteiId 工程ID
T14Koutei.kouteiMei 工程名
T14Koutei.kaishiBi 開始日
T14Koutei.shuryoBi 終了日
T14Koutei.sagyokuCd 作業区CD
T14Koutei.oyaKouteiId 親工程ID
T14Koutei.insertTs 作成タイムスタンプ
T14Koutei.insertUserId 作成者
T14Koutei.updateTs 更新タイムスタンプ
T14Koutei.updateUserId 更新者

T14KouteiGrid.kouteiId 工程ID
T14KouteiGrid.kouteiMei 工程名
T14KouteiGrid.kaishiBi 開始日
T14KouteiGrid.shuryoBi 終了日
T14KouteiGrid.sagyokuCd 作業区CD
T14KouteiGrid.oyaKouteiId 親工程ID
T14KouteiGrid.insertTs 作成タイムスタンプ
T14KouteiGrid.insertUserId 作成者
T14KouteiGrid.updateTs 更新タイムスタンプ
T14KouteiGrid.updateUserId 更新者
