V00YojitsuS.title   VIEW検索
V00YojitsuS.h2      VIEW検索
V00YojitsuS.legend  VIEW検索
V00Yojitsu.add      VIEW追加
V00Yojitsu.title    VIEW
V00Yojitsu.h2       VIEW
V00Yojitsu.legend   VIEW
V00Yojitsu.h3       VIEW一覧

V00Yojitsu.kouteiId 工程ID
V00Yojitsu.kouteiTx 工程名
V00Yojitsu.kaishiBi 開始日
V00Yojitsu.shuryoBi 終了日
V00Yojitsu.oyaKouteiId 親工程ID
V00Yojitsu.jisshiBi 実施日
V00Yojitsu.kanryoBi 完了日

V00YojitsuGrid.kouteiId 工程ID
V00YojitsuGrid.kouteiTx 工程名
V00YojitsuGrid.kaishiBi 開始日
V00YojitsuGrid.shuryoBi 終了日
V00YojitsuGrid.oyaKouteiId 親工程ID
V00YojitsuGrid.jisshiBi 実施日
V00YojitsuGrid.kanryoBi 完了日
