V13FuriwakeS.title   VIEW検索
V13FuriwakeS.h2      VIEW検索
V13FuriwakeS.legend  VIEW検索
V13Furiwake.add      VIEW追加
V13Furiwake.title    VIEW
V13Furiwake.h2       VIEW
V13Furiwake.legend   VIEW
V13Furiwake.h3       VIEW一覧

V13Furiwake.tableName table_name
V13Furiwake.srcIdDestId SRC_ID$DEST_ID
V13Furiwake.info info

V13FuriwakeGrid.tableName table_name
V13FuriwakeGrid.srcIdDestId SRC_ID$DEST_ID
V13FuriwakeGrid.info info
