V13FuriwakeS.title   振分ビュー検索
V13FuriwakeS.h2      振分ビュー検索
V13FuriwakeS.legend  振分ビュー検索
V13Furiwake.add      振分ビュー追加
V13Furiwake.title    振分ビュー
V13Furiwake.h2       振分ビュー
V13Furiwake.legend   振分ビュー
V13Furiwake.h3       振分ビュー一覧

V13Furiwake.tableName テーブル名
V13Furiwake.srcIdDestId 振分ID
V13Furiwake.info 情報

V13FuriwakeGrid.tableName テーブル名
V13FuriwakeGrid.srcIdDestId 振分ID
V13FuriwakeGrid.info 情報
