V13HenkanS.title   変換ビュー検索
V13HenkanS.h2      変換ビュー検索
V13HenkanS.legend  変換ビュー検索
V13Henkan.add      変換ビュー追加
V13Henkan.title    変換ビュー
V13Henkan.h2       変換ビュー
V13Henkan.legend   変換ビュー
V13Henkan.h3       変換ビュー一覧

V13Henkan.tableName テーブル名
V13Henkan.srcId 変換元ID
V13Henkan.destInfo 変換元情報

V13HenkanGrid.tableName テーブル名
V13HenkanGrid.srcId 変換元ID
V13HenkanGrid.destInfo 変換元情報
