V14FukaSagyokuS.title   VIEW検索
V14FukaSagyokuS.h2      VIEW検索
V14FukaSagyokuS.legend  VIEW検索
V14FukaSagyoku.add      VIEW追加
V14FukaSagyoku.title    VIEW
V14FukaSagyoku.h2       VIEW
V14FukaSagyoku.legend   VIEW
V14FukaSagyoku.h3       VIEW一覧

V14FukaSagyoku.labels labels
V14FukaSagyoku.type type
V14FukaSagyoku.stack 作業区CD
V14FukaSagyoku.label 作業区CD
V14FukaSagyoku.data DATA

V14FukaSagyokuGrid.labels labels
V14FukaSagyokuGrid.type type
V14FukaSagyokuGrid.stack 作業区CD
V14FukaSagyokuGrid.label 作業区CD
V14FukaSagyokuGrid.data DATA
