V14FukaSagyokuS.title   作業区負荷検索
V14FukaSagyokuS.h2      作業区負荷検索
V14FukaSagyokuS.legend  作業区負荷検索
V14FukaSagyoku.add      作業区負荷追加
V14FukaSagyoku.title    作業区負荷
V14FukaSagyoku.h2       作業区負荷
V14FukaSagyoku.legend   作業区負荷
V14FukaSagyoku.h3       作業区負荷一覧

V14FukaSagyoku.labels labels
V14FukaSagyoku.type type
V14FukaSagyoku.stack stack
V14FukaSagyoku.label label
V14FukaSagyoku.data DATA

V14FukaSagyokuGrid.labels labels
V14FukaSagyokuGrid.type type
V14FukaSagyokuGrid.stack stack
V14FukaSagyokuGrid.label label
V14FukaSagyokuGrid.data DATA
