V14FukaKadobiS.title   稼働日負荷検索
V14FukaKadobiS.h2      稼働日負荷検索
V14FukaKadobiS.legend  稼働日負荷検索
V14FukaKadobi.add      稼働日負荷追加
V14FukaKadobi.title    稼働日負荷
V14FukaKadobi.h2       稼働日負荷
V14FukaKadobi.legend   稼働日負荷
V14FukaKadobi.h3       稼働日負荷一覧

V14FukaKadobi.labels labels
V14FukaKadobi.type type
V14FukaKadobi.stack stack
V14FukaKadobi.label label
V14FukaKadobi.data DATA

V14FukaKadobiGrid.labels labels
V14FukaKadobiGrid.type type
V14FukaKadobiGrid.stack stack
V14FukaKadobiGrid.label label
V14FukaKadobiGrid.data DATA
