V14FukaKadobiS.title   VIEW検索
V14FukaKadobiS.h2      VIEW検索
V14FukaKadobiS.legend  VIEW検索
V14FukaKadobi.add      VIEW追加
V14FukaKadobi.title    VIEW
V14FukaKadobi.h2       VIEW
V14FukaKadobi.legend   VIEW
V14FukaKadobi.h3       VIEW一覧

V14FukaKadobi.labels labels
V14FukaKadobi.type type
V14FukaKadobi.stack stack
V14FukaKadobi.label 作業区CD
V14FukaKadobi.data DATA

V14FukaKadobiGrid.labels labels
V14FukaKadobiGrid.type type
V14FukaKadobiGrid.stack stack
V14FukaKadobiGrid.label 作業区CD
V14FukaKadobiGrid.data DATA
