V14YojitsuS.title   VIEW検索
V14YojitsuS.h2      VIEW検索
V14YojitsuS.legend  VIEW検索
V14Yojitsu.add      VIEW追加
V14Yojitsu.title    VIEW
V14Yojitsu.h2       VIEW
V14Yojitsu.legend   VIEW
V14Yojitsu.h3       VIEW一覧

V14Yojitsu.kouteiId koutei_id
V14Yojitsu.kouteiTx koutei_tx
V14Yojitsu.kaishiBi kaishi_bi
V14Yojitsu.shuryoBi shuryo_bi
V14Yojitsu.sagyokuCd sagyoku_cd
V14Yojitsu.oyaKouteiId oya_koutei_id
V14Yojitsu.jisshiBi jisshi_bi
V14Yojitsu.kanryoBi kanryo_bi
V14Yojitsu.kouteiPath koutei_path
V14Yojitsu.root root
V14Yojitsu.dependencies dependencies

V14YojitsuGrid.kouteiId koutei_id
V14YojitsuGrid.kouteiTx koutei_tx
V14YojitsuGrid.kaishiBi kaishi_bi
V14YojitsuGrid.shuryoBi shuryo_bi
V14YojitsuGrid.sagyokuCd sagyoku_cd
V14YojitsuGrid.oyaKouteiId oya_koutei_id
V14YojitsuGrid.jisshiBi jisshi_bi
V14YojitsuGrid.kanryoBi kanryo_bi
V14YojitsuGrid.kouteiPath koutei_path
V14YojitsuGrid.root root
V14YojitsuGrid.dependencies dependencies
