V14YojitsuS.title   予実検索
V14YojitsuS.h2      予実検索
V14YojitsuS.legend  予実検索
V14Yojitsu.add      予実追加
V14Yojitsu.title    予実
V14Yojitsu.h2       予実
V14Yojitsu.legend   予実
V14Yojitsu.h3       予実一覧

V14Yojitsu.kouteiId koutei_id
V14Yojitsu.kouteiTx koutei_tx
V14Yojitsu.kaishiYmd kaishi_ymd
V14Yojitsu.shuryoYmd shuryo_ymd
V14Yojitsu.sagyokuCd sagyoku_cd
V14Yojitsu.oyaKouteiId oya_koutei_id
V14Yojitsu.jisshiYmd jisshi_ymd
V14Yojitsu.kanryoYmd kanryo_ymd
V14Yojitsu.dependencies dependencies
V14Yojitsu.kouteiPath koutei_path
V14Yojitsu.root root

V14YojitsuGrid.kouteiId koutei_id
V14YojitsuGrid.kouteiTx koutei_tx
V14YojitsuGrid.kaishiYmd kaishi_ymd
V14YojitsuGrid.shuryoYmd shuryo_ymd
V14YojitsuGrid.sagyokuCd sagyoku_cd
V14YojitsuGrid.oyaKouteiId oya_koutei_id
V14YojitsuGrid.jisshiYmd jisshi_ymd
V14YojitsuGrid.kanryoYmd kanryo_ymd
V14YojitsuGrid.dependencies dependencies
V14YojitsuGrid.kouteiPath koutei_path
V14YojitsuGrid.root root
