V14YojitsuS.title   VIEW検索
V14YojitsuS.h2      VIEW検索
V14YojitsuS.legend  VIEW検索
V14Yojitsu.add      VIEW追加
V14Yojitsu.title    VIEW
V14Yojitsu.h2       VIEW
V14Yojitsu.legend   VIEW
V14Yojitsu.h3       VIEW一覧

V14Yojitsu.kouteiId 工程ID
V14Yojitsu.kouteiTx 工程名
V14Yojitsu.kaishiBi 開始日
V14Yojitsu.shuryoBi 終了日
V14Yojitsu.sagyokuCd 作業区CD
V14Yojitsu.oyaKouteiId 親工程ID
V14Yojitsu.jisshiBi 実施日
V14Yojitsu.kanryoBi 完了日

V14YojitsuGrid.kouteiId 工程ID
V14YojitsuGrid.kouteiTx 工程名
V14YojitsuGrid.kaishiBi 開始日
V14YojitsuGrid.shuryoBi 終了日
V14YojitsuGrid.sagyokuCd 作業区CD
V14YojitsuGrid.oyaKouteiId 親工程ID
V14YojitsuGrid.jisshiBi 実施日
V14YojitsuGrid.kanryoBi 完了日
