/*
SELECT CONCAT ('DROP TABLE ', table_name, ' CASCADE;') AS '--' FROM information_schema.tables WHERE table_schema = 'emarf' AND table_type = 'BASE TABLE'
UNION
SELECT CONCAT ('DROP VIEW ', table_name, ';') AS '--' FROM information_schema.views WHERE table_schema = 'emarf' 
*/
--
DROP TABLE mhr_busho CASCADE;
DROP TABLE mhr_shokui CASCADE;
DROP TABLE mhr_shokui_ninka CASCADE;
DROP TABLE mhr_user CASCADE;
DROP TABLE mhr_user_pos CASCADE;
DROP TABLE msy_kadobi CASCADE;
DROP TABLE msy_kbn CASCADE;
DROP TABLE msy_kbn_val CASCADE;
DROP TABLE msy_tax CASCADE;
DROP TABLE msy_tsuka CASCADE;
DROP TABLE tb0_entity CASCADE;
DROP TABLE tb0_nokey CASCADE;
DROP TABLE tb1_cdref CASCADE;
DROP TABLE tb1_combo1 CASCADE;
DROP TABLE tb1_combo2 CASCADE;
DROP TABLE tb1_idbn CASCADE;
DROP TABLE tb1_idref CASCADE;
DROP TABLE tb1_noref CASCADE;
DROP TABLE tb1_refer1 CASCADE;
DROP TABLE tb1_refer2 CASCADE;
DROP TABLE tb1_refer3 CASCADE;
DROP TABLE tb1_saiki CASCADE;
DROP TABLE tb2_eldest CASCADE;
DROP TABLE tb2_foster CASCADE;
DROP TABLE tb2_younger CASCADE;
DROP TABLE tb2_youngest CASCADE;
DROP TABLE tb3_begin CASCADE;
DROP TABLE tb3_begin_his CASCADE;
DROP TABLE tb4_ko CASCADE;
DROP TABLE tb4_ko_dinks CASCADE;
DROP TABLE tb4_ko_orphans CASCADE;
DROP TABLE tb4_mago CASCADE;
DROP TABLE tb4_oya CASCADE;
DROP TABLE tb5_derive CASCADE;
DROP TABLE tb5_merge CASCADE;
DROP TABLE tb5_prev CASCADE;
DROP TABLE tb5_prev_det CASCADE;
DROP TABLE tb5_reborn CASCADE;
DROP TABLE tb5_reborn_det CASCADE;
DROP TABLE tb6_derive1 CASCADE;
DROP TABLE tb6_derive1_det CASCADE;
DROP TABLE tb6_derive2 CASCADE;
DROP TABLE tb6_derive2_det CASCADE;
DROP TABLE tb6_org CASCADE;
DROP TABLE tb6_org_det CASCADE;
DROP TABLE tb7_sum CASCADE;
DROP TABLE tb7_unit1 CASCADE;
DROP TABLE tb7_unit2 CASCADE;
DROP TABLE tb8_choice CASCADE;
DROP TABLE tb8_prev2 CASCADE;
DROP TABLE tb8_reborn2 CASCADE;
DROP TABLE tb8_sum2 CASCADE;
DROP TABLE tb8_sum3 CASCADE;
DROP TABLE tb8_tasho1 CASCADE;
DROP TABLE tb8_tasho2 CASCADE;
DROP TABLE tb8_unit3 CASCADE;
DROP TABLE tb8_unit4 CASCADE;
DROP TABLE tb9_dest CASCADE;
DROP TABLE tb9_src CASCADE;
DROP VIEW tb9_furiwake;
DROP VIEW tb9_henkan;
