SELECT
      a."BRO_ID" AS "BRO_ID"
    , a."ELDEST_INFO" AS "ELDEST_INFO"
    , TO_CHAR (a."INSERT_TS", 'YYYY-MM-DD HH24:MI:SS.FF3') AS "INSERT_TS"
    , a."INSERT_USER_ID" AS "INSERT_USER_ID"
    , (SELECT r0."USER_SEI" FROM MHR_USER r0 WHERE r0."USER_ID" = a."INSERT_USER_ID") AS "INSERT_USER_SEI"
    , TO_CHAR (a."UPDATE_TS", 'YYYY-MM-DD HH24:MI:SS.FF3') AS "UPDATE_TS"
    , a."UPDATE_USER_ID" AS "UPDATE_USER_ID"
    , (SELECT r1."USER_SEI" FROM MHR_USER r1 WHERE r1."USER_ID" = a."UPDATE_USER_ID") AS "UPDATE_USER_SEI"
    , c1."YOUNGER_INFO" AS "T02_YOUNGER.YOUNGER_INFO"
    , TO_CHAR (c1."UPDATE_TS", 'YYYY-MM-DD HH24:MI:SS.FF3') AS "T02_YOUNGER.UPDATE_TS"
    , c2."YOUNGEST_INFO" AS "T02_YOUNGEST.YOUNGEST_INFO"
    , TO_CHAR (c2."UPDATE_TS", 'YYYY-MM-DD HH24:MI:SS.FF3') AS "T02_YOUNGEST.UPDATE_TS"
FROM
    T02_ELDEST a 
    LEFT OUTER JOIN T02_YOUNGER c1 
        ON 1 = 1 
        AND c1.BRO_ID = a.BRO_ID 
    LEFT OUTER JOIN T02_YOUNGEST c2 
        ON 1 = 1 
        AND c2.BRO_ID = a.BRO_ID 
WHERE
    1 = 1 
    AND a."BRO_ID" = :bro_id 
    AND UPPER (RTRIM (RTRIM (a."ELDEST_INFO"), '　')) LIKE UPPER ('%' || :eldest_info || '%') 
    AND a."INSERT_TS" = TO_TIMESTAMP (REPLACE (SUBSTR (:insert_ts, 0, 23), 'T', ' '), 'YYYY-MM-DD HH24:MI:SS.FF3') 
    AND a."INSERT_TS" >= TO_TIMESTAMP (REPLACE (SUBSTR (:insert_ts_1 , 0, 23), 'T', ' '), 'YYYY-MM-DD HH24:MI:SS.FF3')
    AND a."INSERT_TS" <= TO_TIMESTAMP (REPLACE (SUBSTR (:insert_ts_2 , 0, 23), 'T', ' '), 'YYYY-MM-DD HH24:MI:SS.FF3')
    AND a."INSERT_USER_ID" = :insert_user_id 
    AND a."UPDATE_TS" = TO_TIMESTAMP (REPLACE (SUBSTR (:update_ts, 0, 23), 'T', ' '), 'YYYY-MM-DD HH24:MI:SS.FF3') 
    AND a."UPDATE_TS" >= TO_TIMESTAMP (REPLACE (SUBSTR (:update_ts_1 , 0, 23), 'T', ' '), 'YYYY-MM-DD HH24:MI:SS.FF3')
    AND a."UPDATE_TS" <= TO_TIMESTAMP (REPLACE (SUBSTR (:update_ts_2 , 0, 23), 'T', ' '), 'YYYY-MM-DD HH24:MI:SS.FF3')
    AND a."UPDATE_USER_ID" = :update_user_id 
ORDER BY
    a."BRO_ID"
