nav.dt.HR HR
nav.MhrBushoS 部署マスタ
nav.MhrShokuiS 職位マスタ
nav.MhrShokuiNinkaS 認可マスタ
nav.MhrUserS ユーザマスタ
nav.MhrUserPosS 所属マスタ
nav.dt.00 00
nav.T00EntityS エンティティ
nav.T00NokeyS キーなし
nav.T00UniqueS ユニークキー
nav.dt.01 01
nav.T01EldestS 長兄
nav.T01FosterS 里子
nav.T01YoungerS 弟
nav.T01YoungestS 末弟
nav.dt.02 02
nav.T02OyaS 親
nav.dt.03 03
nav.T03StatusKbS 決裁フロー
nav.T03TransS 変遷
nav.T03TransHisS 変遷履歴
nav.dt.04 04
nav.M04Ref1S マスタ参照１
nav.M04Ref2S マスタ参照２
nav.M04Ref3S マスタ参照３
nav.T04Comp1S 複合１
nav.dt.05 05
nav.M05CdS CDマスタ
nav.M05IdS IDマスタ
nav.M05NoS NOマスタ
nav.M05SaikiS 再帰
nav.dt.06 06
nav.T06PrevS 前世
nav.T06RebornS 転生
nav.dt.07 07
nav.T07Derive1S 派生１
nav.T07Derive2S 派生２
nav.T07OrgS 起源
nav.dt.08 08
nav.T08Kisei1S 寄生１
nav.T08Kisei2S 寄生２
nav.T08KyoseiS 共生
nav.dt.09 09
nav.T09ChoiceS 選択
nav.T09Koho1S 候補１
nav.T09Koho2S 候補２
nav.dt.10 10
nav.T10Grp1S 集団１
nav.T10Grp2S 集団２
nav.T10SumS 集約
nav.dt.11 11
nav.T11Prev2S 前世２
nav.T11Reborn2S 転生２
nav.T11Tasho1S 他生１
nav.dt.12 12
nav.T12Koho3S 候補３
nav.T12Reborn3S 転生３
nav.T12Tasho2S 他生２
nav.dt.13 13
nav.T13DestS 変換先
nav.T13SrcS 変換元
nav.V13FuriwakeS 振分ビュー
nav.V13HenkanS 変換ビュー
nav.dt.14 14
nav.T14JissekiS 実績
nav.T14KouteiS 工程
nav.V14FukaKadobiS 稼働日負荷
nav.V14FukaSagyokuS 作業区負荷
nav.V14YojitsuS 予実
nav.V14YojitsuG 予実
nav.dt.SY SY
nav.MsyKadobiS 稼働日マスタ
nav.MsyKbnS 区分マスタ
nav.MsyTaxS 税マスタ
nav.MsyTsukaS 通貨マスタ
